# Generated by Django 3.0.3 on 2020-02-28 18:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auction_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_date',
            field=models.DateTimeField(blank=True, choices=[(datetime.datetime(2020, 2, 29, 18, 17, 27, 704283, tzinfo=utc), '24H'), (datetime.datetime(2020, 3, 3, 18, 17, 27, 704283, tzinfo=utc), '4 Days'), (datetime.datetime(2020, 3, 11, 18, 17, 27, 704283, tzinfo=utc), '12 days'), (datetime.datetime(2020, 3, 23, 18, 17, 27, 704283, tzinfo=utc), '24 Days')], null=True, verbose_name='Auction Period'),
        ),
    ]
