# Generated by Django 3.0.3 on 2020-02-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_store', '0004_remove_order_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='known_owners',
        ),
        migrations.AddField(
            model_name='item',
            name='previous_owners',
            field=models.CharField(default='...', max_length=200, verbose_name='Previous Owners'),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_date',
            field=models.DateTimeField(blank=True, choices=[('24H', '24H'), ('3 Days', '3 Days'), ('1 Week', '1 Week'), ('3 Weeks', '3 Weeks')], null=True),
        ),
    ]
