# Generated by Django 3.0.3 on 2020-02-27 15:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auction_store', '0008_auto_20200227_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_date',
            field=models.DateTimeField(blank=True, choices=[(datetime.datetime(2020, 2, 27, 15, 48, 22, 255657, tzinfo=utc), 'Test'), (datetime.datetime(2020, 2, 28, 15, 47, 22, 255657, tzinfo=utc), '24H'), (datetime.datetime(2020, 3, 1, 15, 47, 22, 255657, tzinfo=utc), '3 Days'), (datetime.datetime(2020, 3, 5, 15, 47, 22, 255657, tzinfo=utc), '1 Week'), (datetime.datetime(2020, 3, 19, 15, 47, 22, 255657, tzinfo=utc), '3 Weeks')], null=True, verbose_name='Auction Period'),
        ),
        migrations.AlterField(
            model_name='item',
            name='previous_owners',
            field=models.CharField(max_length=200, verbose_name='Previous Owners'),
        ),
    ]
