# Generated by Django 3.0.3 on 2020-02-28 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auction_store', '0015_auto_20200227_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_date',
            field=models.DateTimeField(blank=True, choices=[(datetime.datetime(2020, 2, 29, 14, 21, 55, 964994, tzinfo=utc), '24H'), (datetime.datetime(2020, 3, 3, 14, 21, 55, 964994, tzinfo=utc), '4 Days'), (datetime.datetime(2020, 3, 11, 14, 21, 55, 964994, tzinfo=utc), '12 days'), (datetime.datetime(2020, 3, 23, 14, 21, 55, 964994, tzinfo=utc), '24 Days')], null=True, verbose_name='Auction Period'),
        ),
    ]
