# Generated by Django 3.0.3 on 2020-02-28 16:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auction_store', '0016_auto_20200228_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_date',
            field=models.DateTimeField(blank=True, choices=[(datetime.datetime(2020, 2, 29, 16, 6, 36, 585225, tzinfo=utc), '24H'), (datetime.datetime(2020, 3, 3, 16, 6, 36, 585225, tzinfo=utc), '4 Days'), (datetime.datetime(2020, 3, 11, 16, 6, 36, 585225, tzinfo=utc), '12 days'), (datetime.datetime(2020, 3, 23, 16, 6, 36, 585225, tzinfo=utc), '24 Days')], null=True, verbose_name='Auction Period'),
        ),
    ]
