# Generated by Django 2.1.7 on 2020-01-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='item',
        ),
    ]
