# Generated by Django 2.1.7 on 2020-01-11 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
