# Generated by Django 2.0 on 2019-12-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_desc', models.TextField()),
                ('item_price', models.IntegerField()),
                ('in_auction', models.BooleanField()),
                ('item_bid_start_date', models.DateTimeField(auto_now=True)),
                ('item_bid_end_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
