# Generated by Django 2.1.7 on 2020-01-05 14:53

import auction_store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_date',
            field=models.DateTimeField(default=auction_store.models.dtime),
        ),
    ]
