# Generated by Django 2.1.7 on 2020-02-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_store', '0002_remove_item_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='history_active',
            field=models.BooleanField(default=True),
        ),
    ]
