# Generated by Django 2.1.7 on 2020-01-26 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction_store', '0002_auto_20200126_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sold_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='item',
            name='sold_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
