# Generated by Django 2.1.7 on 2020-01-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_store', '0002_auto_20200105_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='in_auction',
            field=models.BooleanField(default=False),
        ),
    ]
