# Generated by Django 2.1.7 on 2020-01-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_store', '0002_auto_20200108_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='start_auction_price',
            field=models.IntegerField(null=True),
        ),
    ]
