# Generated by Django 2.1.7 on 2020-01-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_store', '0003_auto_20200108_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='start_auction_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
