# Generated by Django 2.1.7 on 2020-01-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_store', '0003_auto_20200128_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
