# Generated by Django 2.1.7 on 2020-02-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_store', '0003_item_history_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='history_active',
            new_name='seller_active',
        ),
        migrations.AddField(
            model_name='item',
            name='buyer_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='winner_active',
            field=models.BooleanField(default=False),
        ),
    ]
