# Generated by Django 2.1.7 on 2020-01-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_store', '0004_auto_20200115_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('MILITARY', 'Military'), ('PRIVATE', 'Private'), ('TOOLS', 'Tools'), ('TREASURE', 'Treasure'), ('WRITINGS', 'Writings'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
