# Generated by Django 2.0 on 2019-12-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_store', '0004_auto_20191216_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='items_pics'),
        ),
    ]
