# Generated by Django 2.1.7 on 2020-02-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_store', '0004_auto_20200203_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='short',
            field=models.CharField(default='Short Description', max_length=50, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.TextField(verbose_name='History'),
        ),
    ]
