# Generated by Django 2.1.7 on 2020-01-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_store', '0005_auto_20200115_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(verbose_name='Price\\(less than\\)'),
        ),
    ]
