# Generated by Django 2.1.7 on 2020-02-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_store', '0007_auto_20200208_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(verbose_name='Price (EURO)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_auction_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Auction Price (EURO)'),
        ),
    ]
