# Generated by Django 2.1.7 on 2020-02-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_store', '0008_auto_20200208_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.TextField(max_length=900, verbose_name='History'),
        ),
    ]
