# Generated by Django 2.1.7 on 2020-01-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_store', '0009_auto_20200117_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bought_at_auction',
            field=models.BooleanField(default=False),
        ),
    ]
