# Generated by Django 2.1.7 on 2020-01-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='empty',
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
