# Generated by Django 2.1.7 on 2020-02-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200203_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='history_checked',
            field=models.BooleanField(default=False),
        ),
    ]
