# Generated by Django 2.1.7 on 2020-02-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_account_history_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='seller_active',
            field=models.BooleanField(default=True),
        ),
    ]
